### ISSUE TITLE
Porting portalocker to use msvcrt instead of win32con

### ISSUE THREAD

**Issue by techtonik** [WoLpH/portalocker#2]
If you compare http://code.activestate.com/recipes/65203-portalocker-cross-platform-posixnt-api-for-flock-s/ with file in this repo, you will notice a lot of meaningless changes. I'd revert the quotes back to original, because there are a lot of portalocker copies out there that needs to be synced.

**Comment by WoLpH** [comment]
@techtonik just letting you know, I haven't forgotten about this issue, I guess you're right that merging to a single file can be convenient for people to integrate into their own projects, for maintenance however I prefer to keep the files separate as it improves readability. So I'll see if I can make Travis automatically merge the separate modules to a single module.

I'll also merge the msvcrt code (assuming I can still find it since Google code is down now), since apparently the code is currently already broken on windows :(
