### ISSUE TITLE
Shared locks with msvcrt backend

### ISSUE THREAD

**Issue by matekatona** [WoLpH/portalocker#29]
I wrote a script a while ago using portalocker 0.5.5, which locked a file with `LOCK_SH | LOCK_NB`, then copied it with `shutil.copyfile()`. This prevented modifying the file during copying (large files, shared network drives).

I recently upgraded to 1.0.0, then the copy failed with a Permission denied error. I checked the changes, and verified, that the old `win32file.LockFileEx()` function allows `shutil.copyfile()` to access the file locked with a shared lock (but prevents modifications), but the new `msvcrt.locking()` function does not (I solved my issue by using `shutil.copyfileobj()` instead)

I checked the documentation of [`msvcrt.locking()`](https://msdn.microsoft.com/en-us/library/8054ew2f.aspx) (which is used since 0.6), and it says nothing about sharing the lock with other processes. It even states, that `_LK_NBRLCK` (equivalent to `LOCK_SH | LOCK_NB`) is the same as `_LK_NBLCK` (equivalent to `LOCK_EX | LOCK_NB`). 

Does this still count as a shared lock?

**Comment by WoLpH** [comment]
Sorry for the slow response, I completely forgot to reply.

Since I'm not a windows user myself it's a bit hard for me to replicate these issues unfortunately. Judging by your results however, I think it might be a good idea if I revert some of the code to offer both options. It might take a while however as I'm quite busy right now.

I have made version 0.5.7 visible on Pypi again which should still function for you: https://pypi.python.org/pypi/portalocker/0.5.7

**Comment by matekatona** [comment]
Thanks, and I'm sorry for my slow response too :D 

I can use 1.0.0 now, as I don't really need a shared lock. 
I'll try to implement a fallback to the old backend when requesting a shared lock, since I have some spare time. We'll meet in a pull request :)

**Comment by WoLpH** [comment]
That would be great! Thanks :)

**Comment by WoLpH** [comment]
Thanks for all the help, I've pushed a new release which takes care of the shared locking issues
