### ISSUE TITLE
Lock file gets blocked on Windows if put in user home directory and not unlocked explicitly

### ISSUE THREAD

**Issue by olegver** [WoLpH/portalocker#49]
This is more a question for now, since I'm trying to find what the exact problem is.

I work on Windows 10 and have a problem with a lock file at ~/.myapp/lock.

I used a library called [msal-extensions](https://github.com/AzureAD/microsoft-authentication-extensions-for-python), which relies on portalocker to lock the token cache. The details are not important, here is the code of their [lock class](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/dev/msal_extensions/cache_lock.py):
```python
class CrossPlatLock(object):
    """Offers a mechanism for waiting until another process is finished interacting with a shared
    resource. This is specifically written to interact with a class of the same name in the .NET
    extensions library.
    """
    def __init__(self, lockfile_path):
        self._lockpath = lockfile_path
        self._fh = None

    def __enter__(self):
        pid = os.getpid()

        self._fh = open(self._lockpath, 'wb+', buffering=0)
        portalocker.lock(self._fh, portalocker.LOCK_EX)
        self._fh.write('{} {}'.format(pid, sys.argv[0]).encode('utf-8'))

    def __exit__(self, *args):
        self._fh.close()
        try:
            # Attempt to delete the lockfile. In either of the failure cases enumerated below, it is
            # likely that another process has raced this one and ended up clearing or locking the
            # file for itself.
            os.remove(self._lockpath)
        except OSError as ex:
            if ex.errno != errno.ENOENT and ex.errno != errno.EACCES:
                raise
```
As you can see, upon exit the file handle is closed and then removed (relying on portalocker to unlock it). However the file (or something) remains in the filesystem and becomes completely blocked by an unknown process (tried processexplorer and handle to figure it out - I can only see that it's blocked by SYSTEM). As a result the consequent calls result in 'Access denied' exception. 

I've tried to play with it and found out that:
- if I remove writing to the file inside `__enter__` - it works;
- if I explicitly call `portalocker.unlock` after closing the file inside `__exit__` - it also works.

Can you provide any help/thoughts on where the problem is? I've submitted [a bug to msal-extensions](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/issues/42) as well, but they also asked me to check with portalocker.

**Comment by WoLpH** [comment]
Looking at the code my theory would be that it's not unlocking because `self._fh` is not cleared. At least, that's the only difference I can see between their code and the one I'm using: https://github.com/WoLpH/portalocker/blob/e5e7d760488539857fdeff65231d40c2a1dcdd88/portalocker/utils.py#L165-L169

Having that said, I think the entire `CrossPlatLock` could be replaced with `portalocker.Lock`. They do roughly the same and I'm guessing that `portalocker.Lock` has been tested by many more people :)

**Comment by rayluo** [comment]
Hi @olegver , in your investigation, did you have to "explicitly call `portalocker.unlock` AFTER or BEFORE closing the file"? Your description in this thread and [the other thread](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/issues/42).

@WoLpH , based on the latest conversation on this thread, will you consider adding that explicitly call `portalocker.unlock` into `portalocker.Lock`? That alone would become a big selling point for us adopting your `Lock`. :-)

**Comment by rayluo** [comment]
@WoLpH , to be clear, I was not suggesting you to include all the non-standard behavior into `portalocker.Lock`. Instead, only one new line, `portalocker.unlock(self._fh)`, is needed to be inserted into between line 167 and line 168 here.

https://github.com/WoLpH/portalocker/blob/e5e7d760488539857fdeff65231d40c2a1dcdd88/portalocker/utils.py#L165-L169

Let me know if you prefer I create a PR for that.

CC: @olegver

**Comment by WoLpH** [comment]
@rayluo no need, I'll create a new release right away :)

**Comment by WoLpH** [comment]
The new release is online

**Comment by rayluo** [comment]
Thanks @WoLpH for prompt response!

Just want to double check, is this improvement released in version 1.6.0? I need to be sure, when/if we would choose to make a dependence on this version.

I deduce that version number from this process:
* There was no new version in [Github release page](https://github.com/WoLpH/portalocker/releases) or in [tags](https://github.com/WoLpH/portalocker/tags)
* The [source code contains an old version number](https://github.com/WoLpH/portalocker/blob/develop/portalocker/__init__.py#L14) (which you might consider to change it soon, and then release a 1.6.1, otherwise `import portalocker; print(portalocker.__version__)` would probably display an incorrect version number.
* There was a [1.6.0 released on PyPI just now](https://pypi.org/project/portalocker/#history)

**Comment by olegver** [comment]
@rayluo: sorry, indeed there is the typo here. I had to close it before closing the file.
Fixed the it in the description.

**Comment by WoLpH** [comment]
@rayluo yes, version `1.6.0` indeed. It seems I forgot to do a `git push`. It's added now :)
